<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><?=$title;?></title>

    <link href="<?=$root_path;?>css/bootstrap.min.css" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="http://cdn.bootcss.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="http://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    <link rel="stylesheet" href="http://cdn.jsdelivr.net/highlight.js/9.3.0/styles/zenburn.min.css">
</head>
<body>
<div class="container">
    <ul class="list-unstyled navigation">
        <?php foreach($chapters as $md=>$chapter){?>
            <li><a href="<?=$chapter['url']?>"><?=$chapter['title']?></a></li>
            <ul>
                <?php foreach($chapter['h2'] as $h2){?>
                    <li><a href="<?=$h2['url']?>"><?=$h2['title']?></a> </li>
                <?php } ?>
            </ul>
        <?php } ?>
    </ul>
</div>
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="http://cdn.bootcss.com/jquery/1.11.3/jquery.min.js"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="<?=$root_path;?>js/bootstrap.min.js"></script>
<script src="http://cdn.jsdelivr.net/highlight.js/9.3.0/highlight.min.js"></script>
<script>hljs.initHighlightingOnLoad();</script>

</body>
</html>